# Generated by Django 5.2.5 on 2025-08-17 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_products_checked', models.IntegerField(default=0)),
                ('total_out_of_stock', models.IntegerField(default=0)),
                ('availability_rate', models.FloatField(default=0.0)),
                ('most_problematic_products', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='days_out_of_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='alert',
            name='product_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_variants',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='out_of_stock_variants',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scrapesession',
            name='availability_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='scrapesession',
            name='out_of_stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapesession',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('variant', models.CharField(blank=True, max_length=200)),
                ('keyword', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('alert_type', models.CharField(choices=[('DAILY_OUTAGE', 'Daily Outage Alert'), ('CONSECUTIVE_DAYS', 'Consecutive Days Alert'), ('FREQUENT_OUTAGE', 'Frequent Outage Alert'), ('RESTOCKING_PATTERN', 'Restocking Pattern Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Priority')], max_length=10)),
                ('outage_count_today', models.IntegerField(default=0)),
                ('consecutive_days', models.IntegerField(default=0)),
                ('total_checks_today', models.IntegerField(default=0)),
                ('last_available_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('product_name', 'variant', 'keyword', 'pincode', 'alert_type')},
            },
        ),
        migrations.CreateModel(
            name='ProductTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('variant', models.CharField(blank=True, max_length=200)),
                ('keyword', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('is_available', models.BooleanField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tracks', to='scraper_app.scrapesession')),
            ],
            options={
                'indexes': [models.Index(fields=['product_name', 'checked_at'], name='scraper_app_product_5d5d3c_idx'), models.Index(fields=['keyword', 'pincode', 'checked_at'], name='scraper_app_keyword_b427c8_idx')],
            },
        ),
    ]
