# Generated by Django 5.2.5 on 2025-08-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0002_dailystocksummary_alter_alert_alert_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='weekly_outages',
            field=models.IntegerField(default=0),
        ),
    ]
